### ISSUE TITLE
Deploy new beta

### ISSUE THREAD

**Issue by AdamFrey** [clojurewerkz/elephant#11]
Any chance you could push the current code to a new beta artifact? My PR (https://github.com/clojurewerkz/elephant/pull/9) was merged back in November, and I'm just hoping I can avoid this warning every time I compile.
```
WARNING: list already refers to: #'clojure.core/list in namespace: clojurewerkz.elephant.charges, being replaced by: #'clojurewerkz.elephant.charges/list
```

Thanks

**Comment by michaelklishin** [comment]
Later this week.

**Comment by acron0** [comment]
@michaelklishin Any chance we can get this change?

**Comment by michaelklishin** [comment]
`beta19` is now up on Clojars.
